"""Add field isDeleted for Note

Revision ID: d7044a17d229
Revises: 7cad57827eb8
Create Date: 2022-04-07 19:50:35.533487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7044a17d229'
down_revision = '7cad57827eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('isDeleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'isDeleted')
    # ### end Alembic commands ###
